# Uncomment if you start the app as root and want to downgrade
# once all privileged actions are completed
#user="wildduck"
#group="wildduck"

# process title and syslog ident
ident="wildduck"

# how many processes to start
processes=1

# default quota storage in MB (can be overriden per user)
maxStorage=1024

# default smtp recipients for 24h (can be overriden per user)
maxRecipients=2000

# default forwarded messages for 24h (can be overriden per user)
maxForwards=2000

# If usernames are not email addresses then use this domain as hostname part
#emailDomain="mydomain.info"

bugsnagCode=""

# Header rules for routing spam
# @include "spamheaders.toml"

[dbs]
# @include "dbs.toml"

[totp]
    # If enabled then encrypt TOTP seed tokens with the secret password. By default TOTP seeds
    # are not encrypted and stored as cleartext. Once set up do not change these values,
    # otherwise decrypting totp seeds is going to fail
    #cipher="aes192"
    #secret="a secret cat"

[attachments]
    # For now there's only a single option for attachment storage
    type="gridstore"
    bucket="attachments"

[log]
    level="silly"
    # log to syslog if true
    # not needed if you run the app as systemd service
    syslog=false

    # delete authentication log entries after 30 days
    # changing this value only affects new entries
    authlogExpireDays=30

[imap]
# @include "imap.toml"

[tls]
# @include "tls.toml"

[lmtp]
# @include "lmtp.toml"

[pop3]
# @include "pop3.toml"

[api]
# @include "api.toml"

[sender]
# @include "sender.toml"

[smtp.setup]
    # Public configuration for SMTP MDA
    hostname="localtest.me"
    secure=false
    port=2587
